[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ALWAYS"

# No healthcheck needed for bastion host
# No ports to expose - Railway SSH handles access